### ISSUE TITLE
prototype todo

### ISSUE THREAD

**Issue by caseyg** [caseyg/thegraphicsoffice#2]
- [x] add content to work
- [x] add content to research
- [x] add prints to shop
- [x] add books to shop
- [x] add content to about
- [x] add images to case studies and give them a layout
- [x] make typer run off of jekyll
- [x] sort content on work into selected and more
- [x] add enough tagging to make homepage + work nav useful
- [x] add footer
- [x] add contact form to footer
- [x] resolve top nav split-link weirdness
